package modul;

import java.sql.*;

public class Database {
	
	Connection con = null;
	String url = "jdbc:mysql:"+System.getenv("homepath")+"/WissLK_MC.db";
	
	public void connect() {
		Connection connection = null;
        try {

            connection = DriverManager.getConnection(url);

            System.out.println("Database created");
        } 
        catch (SQLException e) {
            System.out.println(e.getMessage());
        } 
        finally {
            try {
                if (connection != null) {
                    connection.close();
                }
            } 
            catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
	}
	
	public void createTables() {
		String sql = "-- MySQL Script generated by MySQL Workbench\r\n" + 
				"-- Fri Jun 22 13:14:52 2018\r\n" + 
				"-- Model: New Model    Version: 1.0\r\n" + 
				"-- MySQL Workbench Forward Engineering\r\n" + 
				"\r\n" + 
				"SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;\r\n" + 
				"SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;\r\n" + 
				"SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';\r\n" + 
				"\r\n" + 
				"-- -----------------------------------------------------\r\n" + 
				"-- Schema MCAU\r\n" + 
				"-- -----------------------------------------------------\r\n" + 
				"DROP SCHEMA IF EXISTS `MCAU` ;\r\n" + 
				"\r\n" + 
				"-- -----------------------------------------------------\r\n" + 
				"-- Schema MCAU\r\n" + 
				"-- -----------------------------------------------------\r\n" + 
				"CREATE SCHEMA IF NOT EXISTS `MCAU` DEFAULT CHARACTER SET utf8 ;\r\n" + 
				"USE `MCAU` ;\r\n" + 
				"\r\n" + 
				"-- -----------------------------------------------------\r\n" + 
				"-- Table `MCAU`.`Stats`\r\n" + 
				"-- -----------------------------------------------------\r\n" + 
				"DROP TABLE IF EXISTS `Stats` ;\r\n" + 
				"\r\n" + 
				"CREATE TABLE IF NOT EXISTS `MCAU`.`Stats` (\r\n" + 
				"  `idStats` INT NOT NULL AUTO_INCREMENT,\r\n" + 
				"  `Win` INT NULL,\r\n" + 
				"  `Loss` INT NULL,\r\n" + 
				"  `HoursPlayed` INT NULL,\r\n" + 
				"  PRIMARY KEY (`idStats`))\r\n" + 
				"ENGINE = InnoDB;\r\n" + 
				"\r\n" + 
				"\r\n" + 
				"-- -----------------------------------------------------\r\n" + 
				"-- Table `MCAU`.`User`\r\n" + 
				"-- -----------------------------------------------------\r\n" + 
				"DROP TABLE IF EXISTS `MCAU`.`User` ;\r\n" + 
				"\r\n" + 
				"CREATE TABLE IF NOT EXISTS `MCAU`.`User` (\r\n" + 
				"  `idUser` INT NOT NULL AUTO_INCREMENT,\r\n" + 
				"  `Username` VARCHAR(45) NULL,\r\n" + 
				"  `Learningrpoints` INT NULL,\r\n" + 
				"  `Stats_idStats` INT NOT NULL,\r\n" + 
				"  PRIMARY KEY (`idUser`),\r\n" + 
				"  INDEX `fk_User_Stats_idx` (`Stats_idStats` ASC),\r\n" + 
				"  CONSTRAINT `fk_User_Stats`\r\n" + 
				"    FOREIGN KEY (`Stats_idStats`)\r\n" + 
				"    REFERENCES `MCAU`.`Stats` (`idStats`)\r\n" + 
				"    ON DELETE NO ACTION\r\n" + 
				"    ON UPDATE NO ACTION)\r\n" + 
				"ENGINE = InnoDB;\r\n" + 
				"\r\n" + 
				"\r\n" + 
				"-- -----------------------------------------------------\r\n" + 
				"-- Table `MCAU`.`Tests`\r\n" + 
				"-- -----------------------------------------------------\r\n" + 
				"DROP TABLE IF EXISTS `Tests` ;\r\n" + 
				"\r\n" + 
				"CREATE TABLE IF NOT EXISTS `MCAU`.`Tests` (\r\n" + 
				"  `idTest` INT NOT NULL AUTO_INCREMENT,\r\n" + 
				"  `Fach` VARCHAR(500) NULL,\r\n" + 
				"  `Path` VARCHAR(500) NULL,\r\n" + 
				"  `Name` VARCHAR(200) NOT NULL,\r\n" + 
				"  `User_idUser` INT NOT NULL,\r\n" + 
				"  PRIMARY KEY (`idTest`, `User_idUser`),\r\n" + 
				"  INDEX `fk_Tests_User1_idx` (`User_idUser` ASC),\r\n" + 
				"  CONSTRAINT `fk_Tests_User1`\r\n" + 
				"    FOREIGN KEY (`User_idUser`)\r\n" + 
				"    REFERENCES `MCAU`.`User` (`idUser`)\r\n" + 
				"    ON DELETE NO ACTION\r\n" + 
				"    ON UPDATE NO ACTION)\r\n" + 
				"ENGINE = InnoDB;\r\n" + 
				"\r\n" + 
				"\r\n" + 
				"SET SQL_MODE=@OLD_SQL_MODE;\r\n" + 
				"SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;\r\n" + 
				"SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;\r\n" + 
				"";

	        try (Connection connection = DriverManager.getConnection(url);
	             Statement stmt = connection.createStatement()) {
	            stmt.execute(sql);
	        } catch (SQLException e) {
	            System.out.println(e.getMessage());
	        }
	}
}
